language: csharp
solution: Alexandria.sln
install:
  - nuget restore Alexandria.sln
  - nuget install NUnit.Console -Version 3.7.0 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release Alexandria.sln
  - mono ./testrunner/NUnit.Console.3.7.0/tools/nunit3-console.exe ./Alexandria.Tests/bin/Release/Alexandria.Tests.dll